runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
  secure: always

- url: /newgoal
  static_files: www/newgoal.html
  upload: www/goals.html
  secure: always

- url: /newlog
  static_files: www/newlog.html
  upload: www/newlog.html
  secure: always

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
  secure: always
