runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /goals
  static_files: www/goals.html
  upload: www/goals.html

- url: /logs
  static_files: www/logs.html
  upload: www/logs.html

- url: /newlog
  static_files: www/newlog.html
  upload: www/newlog.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
